### ISSUE TITLE
PID control problem on hard limits

### ISSUE THREAD

**Issue by Gs581** [sas229/CamLab#14]
When the linear axis hits a hard limit (physical or in software) in PID control, the PID controller doesn't turn off and the actuator and linear axis become unresponsive for some time. The hard limit should turn off PID control.

**Comment by sas229** [comment]
I have added logic to try and fix this issue, but I cannot test it here. Pull the latest version of this repo, try it and let me know if it fixes the issue.

**Comment by sas229** [comment]
Now fixed by Federico.
